name: 'Docker Compose Action'
description: 'Use docker compose in steps and remove after action finished (started always in detached mode)'
author: 'asgoodasnew'

# Define your inputs here.
inputs:
  compose-file:
    description: 'Add one or more compose files with relative path'
    required: true
    default: './docker-compose.yml'
  services:
    description: 'Optional services we should start'
    required: false
  compose-options:
    description: 'Optional compose options (see https://docs.docker.com/compose/reference/#command-options-overview-and-help)'
    required: false
  compose-up-options:
    description: 'Optional compose up command options (see https://docs.docker.com/engine/reference/commandline/compose_up/)'
    required: false
  compose-down-options:
    description: 'Optional compose down command options (see https://docs.docker.com/engine/reference/commandline/compose_down/)'
    required: false
    default: '--volumes'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
